name: Example Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Ensure GitHub token has 'id-token: write' permission
  contents: read   # Allows read access to repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (example step)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies (example step)
        run: npm install

      - name: Run tests (example step)
        run: npm test
